---
- hosts: canhat
  roles:

  - role: common  
    tags: [common]

  - role: ros2  
    tags: [ros2]

  - role: canhat  
    tags: [canhat] 
  
  - role: vscode  
    tags: [vscode]

  - role: network-fallback  
    tags: [network-fallback]
     
  - role: brover_soft 
    tags: [brover_soft]