#!/bin/bash
source /home/pi/.ros_params
source /opt/ros/jazzy/local_setup.bash

for _ in {1..30}; do
    ROBOT_IP=$(hostname -I | awk '{print $1}')
    if [ -n "$ROBOT_IP" ]; then
        break
    fi
    sleep 1
done

exec /opt/ros/jazzy/bin/fastdds discovery --server-id 0 --verbose -l "${ROBOT_IP}" -p 11811